// comments in English only
// Auto-generated by scripts/generate-locales.ts
import type { LocalePack } from '../src/precise-compact';

const pack = {
  locale: 'bg',
  labels: {
    thousand: {
      words: {
        one: 'хиляда',
        other: 'хиляди',
      },
      abbr: {
        other: 'хил.',
      },
    },
    million: {
      words: {
        one: 'милион',
        other: 'милиона',
      },
      abbr: {
        other: 'млн.',
      },
    },
    billion: {
      words: {
        one: 'милиард',
        other: 'милиарда',
      },
      abbr: {
        other: 'млрд.',
      },
    },
    trillion: {
      words: {
        one: 'трилион',
        other: 'трилиона',
      },
      abbr: {
        other: 'трлн.',
      },
    },
  },
} as any as LocalePack;

export default pack;
