// comments in English only
// Auto-generated by scripts/generate-locales.ts
import type { LocalePack } from '../src/precise-compact';

const pack = {
  locale: 'bn',
  labels: {
    thousand: {
      words: 'হাজার',
      abbr: 'হা',
    },
    million: {
      words: 'মিলিয়ন',
      abbr: 'মি',
    },
    billion: {
      words: 'বিলিয়ন',
      abbr: 'বি',
    },
    trillion: {
      words: 'ট্রিলিয়ন',
      abbr: 'ট্রি',
    },
  },
} as any as LocalePack;

export default pack;
