
// Auto-generated by scripts/generate-locales.ts
import type { LocalePack } from '../src/precise-compact';

const pack = {
  "locale": "ca",
  "labels": {
    "thousand": {
      "words": "mil",
      "abbr": "k"
    },
    "million": {
      "words": {
        "one": "milió",
        "other": "milions"
      },
      "abbr": {
        "other": "M"
      }
    },
    "billion": {
      "words": {
        "one": "bilió",
        "other": "bilions"
      },
      "abbr": {
        "other": "Bn"
      }
    },
    "trillion": {
      "words": {
        "one": "trilió",
        "other": "trilions"
      },
      "abbr": {
        "other": "Tn"
      }
    }
  }
} as any as LocalePack;

export default pack;
