// comments in English only
// Auto-generated by scripts/generate-locales.ts
import type { LocalePack } from '../src/precise-compact';

const pack = {
  locale: 'de',
  labels: {
    thousand: {
      words: 'tausend',
      abbr: 'Tsd.',
    },
    million: {
      words: {
        one: 'Million',
        other: 'Millionen',
      },
      abbr: {
        other: 'Mio.',
      },
    },
    billion: {
      words: {
        one: 'Milliarde',
        other: 'Milliarden',
      },
      abbr: {
        other: 'Mrd.',
      },
    },
    trillion: {
      words: {
        one: 'Billion',
        other: 'Billionen',
      },
      abbr: {
        other: 'Bio.',
      },
    },
  },
} as any as LocalePack;

export default pack;
