// comments in English only
// Auto-generated by scripts/generate-locales.ts
import type { LocalePack } from '../src/precise-compact';

const pack = {
  locale: 'el',
  labels: {
    thousand: {
      words: {
        one: 'χίλια',
        other: 'χιλιάδες',
      },
      abbr: {
        other: 'χιλ.',
      },
    },
    million: {
      words: {
        one: 'εκατομμύριο',
        other: 'εκατομμύρια',
      },
      abbr: {
        other: 'εκ.',
      },
    },
    billion: {
      words: {
        one: 'δισεκατομμύριο',
        other: 'δισεκατομμύρια',
      },
      abbr: {
        other: 'δισ.',
      },
    },
    trillion: {
      words: {
        one: 'τρισεκατομμύριο',
        other: 'τρισεκατομμύρια',
      },
      abbr: {
        other: 'τρισ.',
      },
    },
  },
} as any as LocalePack;

export default pack;
