// comments in English only
// Auto-generated by scripts/generate-locales.ts
import type { LocalePack } from '../src/precise-compact';

const pack = {
  locale: 'es',
  labels: {
    thousand: {
      words: 'mil',
      abbr: 'k',
    },
    million: {
      words: {
        one: 'millón',
        other: 'millones',
      },
      abbr: {
        other: 'M',
      },
    },
    billion: {
      words: {
        one: 'billón',
        other: 'billones',
      },
      abbr: {
        other: 'Bn',
      },
    },
    trillion: {
      words: {
        one: 'trillón',
        other: 'trillones',
      },
      abbr: {
        other: 'Tn',
      },
    },
  },
} as any as LocalePack;

export default pack;
