// comments in English only
// Auto-generated by scripts/generate-locales.ts
import type { LocalePack } from '../src/precise-compact';

const pack = {
  "locale": "et",
  "labels": {
    "thousand": {
      "words": "tuhat",
      "abbr": "tuh"
    },
    "million": {
      "words": {
        "one": "miljon",
        "other": "miljonit"
      },
      "abbr": {
        "other": "mln"
      }
    },
    "billion": {
      "words": {
        "one": "miljard",
        "other": "miljardit"
      },
      "abbr": {
        "other": "mld"
      }
    },
    "trillion": {
      "words": {
        "one": "biljon",
        "other": "biljonit"
      },
      "abbr": {
        "other": "bln"
      }
    }
  }
} as any as LocalePack;

export default pack;
