
// Auto-generated by scripts/generate-locales.ts
import type { LocalePack } from '../src/precise-compact';

const pack = {
  "locale": "fa",
  "labels": {
    "thousand": {
      "words": "هزار",
      "abbr": "هزار"
    },
    "million": {
      "words": "میلیون",
      "abbr": "می"
    },
    "billion": {
      "words": "میلیارد",
      "abbr": "میلیا"
    },
    "trillion": {
      "words": "تریلیون",
      "abbr": "تر"
    }
  },
  "rules": {
    "rtl": true
  }
} as any as LocalePack;

export default pack;
