// comments in English only
// Auto-generated by scripts/generate-locales.ts
import type { LocalePack } from '../src/precise-compact';

const pack = {
  "locale": "fi",
  "labels": {
    "thousand": {
      "words": "tuhat",
      "abbr": "tuh"
    },
    "million": {
      "words": {
        "one": "miljoona",
        "other": "miljoonat"
      },
      "abbr": {
        "other": "milj."
      }
    },
    "billion": {
      "words": {
        "one": "miljardi",
        "other": "miljardit"
      },
      "abbr": {
        "other": "mrd."
      }
    },
    "trillion": {
      "words": {
        "one": "biljoona",
        "other": "biljoonat"
      },
      "abbr": {
        "other": "blj."
      }
    }
  }
} as any as LocalePack;

export default pack;
