
// Auto-generated by scripts/generate-locales.ts
import type { LocalePack } from '../src/precise-compact';

const pack = {
  "locale": "fil-PH",
  "labels": {
    "thousand": {
      "words": "libo",
      "abbr": "k"
    },
    "million": {
      "words": "milyon",
      "abbr": "M"
    },
    "billion": {
      "words": "bilyon",
      "abbr": "Bn"
    },
    "trillion": {
      "words": "trilyon",
      "abbr": "Tn"
    }
  }
} as any as LocalePack;

export default pack;
