
// Auto-generated by scripts/generate-locales.ts
import type { LocalePack } from '../src/precise-compact';

const pack = {
  "locale": "fr",
  "labels": {
    "thousand": {
      "words": "mille",
      "abbr": "k"
    },
    "million": {
      "words": {
        "one": "million",
        "other": "millions"
      },
      "abbr": {
        "other": "M"
      }
    },
    "billion": {
      "words": {
        "one": "milliard",
        "other": "milliards"
      },
      "abbr": {
        "other": "Md"
      }
    },
    "trillion": {
      "words": {
        "one": "billion",
        "other": "billions"
      },
      "abbr": {
        "other": "Bn"
      }
    }
  },
  "rules": {
    "joiner": " "
  }
} as any as LocalePack;

export default pack;
