// comments in English only
// Auto-generated by scripts/generate-locales.ts
import type { LocalePack } from '../src/precise-compact';

const pack = {
  "locale": "gu",
  "labels": {
    "thousand": {
      "words": "હજાર",
      "abbr": "હ"
    },
    "million": {
      "words": "મિલિયન",
      "abbr": "મિ"
    },
    "billion": {
      "words": "બિલિયન",
      "abbr": "બિ"
    },
    "trillion": {
      "words": "ટ્રિલિયન",
      "abbr": "ટ્રિ"
    }
  }
} as any as LocalePack;

export default pack;
