
// Auto-generated by scripts/generate-locales.ts
import type { LocalePack } from '../src/precise-compact';

const pack = {
  "locale": "he",
  "labels": {
    "thousand": {
      "words": "אלף",
      "abbr": "אלף"
    },
    "million": {
      "words": "מיליון",
      "abbr": "מל׳"
    },
    "billion": {
      "words": "מיליארד",
      "abbr": "מליא׳"
    },
    "trillion": {
      "words": "טריליון",
      "abbr": "טר׳"
    }
  },
  "rules": {
    "rtl": true
  }
} as any as LocalePack;

export default pack;
