
// Auto-generated by scripts/generate-locales.ts
import type { LocalePack } from '../src/precise-compact';

const pack = {
  "locale": "hi",
  "labels": {
    "thousand": {
      "words": "हज़ार",
      "abbr": "ह"
    },
    "million": {
      "words": "मिलियन",
      "abbr": "मि"
    },
    "billion": {
      "words": "बिलियन",
      "abbr": "बि"
    },
    "trillion": {
      "words": "ट्रिलियन",
      "abbr": "ट्रि"
    }
  }
} as any as LocalePack;

export default pack;
