// comments in English only
// Auto-generated by scripts/generate-locales.ts
import type { LocalePack } from '../src/precise-compact';

const pack = {
  locale: 'hr',
  labels: {
    thousand: {
      words: {
        one: 'tisuća',
        few: 'tisuće',
        many: 'tisuća',
        other: 'tisuće',
      },
      abbr: {
        other: 'tis.',
      },
    },
    million: {
      words: {
        one: 'milijun',
        few: 'milijuna',
        many: 'milijuna',
        other: 'milijuna',
      },
      abbr: {
        other: 'mil.',
      },
    },
    billion: {
      words: {
        one: 'milijarda',
        few: 'milijarde',
        many: 'milijardi',
        other: 'milijarde',
      },
      abbr: {
        other: 'mld.',
      },
    },
    trillion: {
      words: {
        one: 'bilijun',
        few: 'bilijuna',
        many: 'bilijuna',
        other: 'bilijuna',
      },
      abbr: {
        other: 'bln.',
      },
    },
  },
} as any as LocalePack;

export default pack;
