// comments in English only
// Auto-generated by scripts/generate-locales.ts
import type { LocalePack } from '../src/precise-compact';

const pack = {
  "locale": "hu",
  "labels": {
    "thousand": {
      "words": "ezer",
      "abbr": "e"
    },
    "million": {
      "words": "millió",
      "abbr": "M"
    },
    "billion": {
      "words": "milliárd",
      "abbr": "Md"
    },
    "trillion": {
      "words": "billió",
      "abbr": "Bl"
    }
  }
} as any as LocalePack;

export default pack;
