// comments in English only
// Auto-generated by scripts/generate-locales.ts
import type { LocalePack } from '../src/precise-compact';

const pack = {
  locale: 'it',
  labels: {
    thousand: {
      words: 'mille',
      abbr: 'k',
    },
    million: {
      words: {
        one: 'milione',
        other: 'milioni',
      },
      abbr: {
        other: 'M',
      },
    },
    billion: {
      words: {
        one: 'miliardo',
        other: 'miliardi',
      },
      abbr: {
        other: 'Mrd',
      },
    },
    trillion: {
      words: {
        one: 'bilione',
        other: 'bilioni',
      },
      abbr: {
        other: 'Bl',
      },
    },
  },
} as any as LocalePack;

export default pack;
