
// Auto-generated by scripts/generate-locales.ts
import type { LocalePack } from '../src/precise-compact';

const pack = {
  "locale": "kn",
  "labels": {
    "thousand": {
      "words": "ಸಾವಿರ",
      "abbr": "ಸಾ"
    },
    "million": {
      "words": "ಮಿಲಿಯನ್",
      "abbr": "ಮಿ"
    },
    "billion": {
      "words": "ಬಿಲಿಯನ್",
      "abbr": "ಬಿ"
    },
    "trillion": {
      "words": "ಟ್ರಿಲಿಯನ್",
      "abbr": "ಟ್ರಿ"
    }
  }
} as any as LocalePack;

export default pack;
