// comments in English only
// Auto-generated by scripts/generate-locales.ts
import type { LocalePack } from '../src/precise-compact';

const pack = {
  locale: 'lt',
  labels: {
    thousand: {
      words: {
        one: 'tūkstantis',
        other: 'tūkstančiai',
      },
      abbr: {
        other: 'tūkst.',
      },
    },
    million: {
      words: {
        one: 'milijonas',
        other: 'milijonai',
      },
      abbr: {
        other: 'mln.',
      },
    },
    billion: {
      words: {
        one: 'milijardas',
        other: 'milijardai',
      },
      abbr: {
        other: 'mlrd.',
      },
    },
    trillion: {
      words: {
        one: 'trilijonas',
        other: 'trilijonai',
      },
      abbr: {
        other: 'trln.',
      },
    },
  },
} as any as LocalePack;

export default pack;
