// comments in English only
// Auto-generated by scripts/generate-locales.ts
import type { LocalePack } from '../src/precise-compact';

const pack = {
  locale: 'lv',
  labels: {
    thousand: {
      words: {
        one: 'tūkstotis',
        other: 'tūkstoši',
      },
      abbr: {
        other: 'tūkst.',
      },
    },
    million: {
      words: {
        one: 'miljons',
        other: 'miljoni',
      },
      abbr: {
        other: 'mln.',
      },
    },
    billion: {
      words: {
        one: 'miljards',
        other: 'miljardi',
      },
      abbr: {
        other: 'mlrd.',
      },
    },
    trillion: {
      words: {
        one: 'triljons',
        other: 'triljoni',
      },
      abbr: {
        other: 'trln.',
      },
    },
  },
} as any as LocalePack;

export default pack;
