
// Auto-generated by scripts/generate-locales.ts
import type { LocalePack } from '../src/precise-compact';

const pack = {
  "locale": "ms-MY",
  "labels": {
    "thousand": {
      "words": "ribu",
      "abbr": "rb"
    },
    "million": {
      "words": "juta",
      "abbr": "jt"
    },
    "billion": {
      "words": "bilion",
      "abbr": "bl"
    },
    "trillion": {
      "words": "trilion",
      "abbr": "tl"
    }
  }
} as any as LocalePack;

export default pack;
