// comments in English only
// Auto-generated by scripts/generate-locales.ts
import type { LocalePack } from '../src/precise-compact';

const pack = {
  locale: 'nb-NO',
  labels: {
    thousand: {
      words: 'tusen',
      abbr: 'tus',
    },
    million: {
      words: {
        one: 'million',
        other: 'millioner',
      },
      abbr: {
        other: 'mill.',
      },
    },
    billion: {
      words: {
        one: 'milliard',
        other: 'milliarder',
      },
      abbr: {
        other: 'mrd.',
      },
    },
    trillion: {
      words: {
        one: 'billion',
        other: 'billioner',
      },
      abbr: {
        other: 'bio.',
      },
    },
  },
} as any as LocalePack;

export default pack;
