// comments in English only
// Auto-generated by scripts/generate-locales.ts
import type { LocalePack } from '../src/precise-compact';

const pack = {
  "locale": "nl",
  "labels": {
    "thousand": {
      "words": "duizend",
      "abbr": "dzd"
    },
    "million": {
      "words": {
        "one": "miljoen",
        "other": "miljoenen"
      },
      "abbr": {
        "other": "M"
      }
    },
    "billion": {
      "words": {
        "one": "miljard",
        "other": "miljarden"
      },
      "abbr": {
        "other": "Md"
      }
    },
    "trillion": {
      "words": {
        "one": "biljoen",
        "other": "biljoenen"
      },
      "abbr": {
        "other": "Bl"
      }
    }
  }
} as any as LocalePack;

export default pack;
