// comments in English only
// Auto-generated by scripts/generate-locales.ts
import type { LocalePack } from '../src/precise-compact';

const pack = {
  "locale": "pt-BR",
  "labels": {
    "thousand": {
      "words": "mil",
      "abbr": "mil"
    },
    "million": {
      "words": {
        "one": "milhão",
        "other": "milhões"
      },
      "abbr": {
        "other": "mi"
      }
    },
    "billion": {
      "words": {
        "one": "bilhão",
        "other": "bilhões"
      },
      "abbr": {
        "other": "bi"
      }
    },
    "trillion": {
      "words": {
        "one": "trilhão",
        "other": "trilhões"
      },
      "abbr": {
        "other": "tri"
      }
    }
  }
} as any as LocalePack;

export default pack;
