// comments in English only
// Auto-generated by scripts/generate-locales.ts
import type { LocalePack } from '../src/precise-compact';

const pack = {
  locale: 'pt-PT',
  labels: {
    thousand: {
      words: 'mil',
      abbr: 'mil',
    },
    million: {
      words: {
        one: 'milhão',
        other: 'milhões',
      },
      abbr: {
        other: 'M',
      },
    },
    billion: {
      words: {
        one: 'mil milhões',
        other: 'mil milhões',
      },
      abbr: {
        other: 'MilM',
      },
    },
    trillion: {
      words: {
        one: 'bilião',
        other: 'biliões',
      },
      abbr: {
        other: 'Bl',
      },
    },
  },
} as any as LocalePack;

export default pack;
