// comments in English only
// Auto-generated by scripts/generate-locales.ts
import type { LocalePack } from '../src/precise-compact';

const pack = {
  "locale": "ro",
  "labels": {
    "thousand": {
      "words": {
        "one": "mie",
        "other": "mii"
      },
      "abbr": {
        "other": "mii"
      }
    },
    "million": {
      "words": {
        "one": "milion",
        "other": "milioane"
      },
      "abbr": {
        "other": "mil."
      }
    },
    "billion": {
      "words": {
        "one": "miliard",
        "other": "miliarde"
      },
      "abbr": {
        "other": "mld."
      }
    },
    "trillion": {
      "words": {
        "one": "bilion",
        "other": "bilioane"
      },
      "abbr": {
        "other": "bln."
      }
    }
  }
} as any as LocalePack;

export default pack;
