// comments in English only
// Auto-generated by scripts/generate-locales.ts
import type { LocalePack } from '../src/precise-compact';

const pack = {
  locale: 'sk',
  labels: {
    thousand: {
      words: {
        one: 'tisíc',
        few: 'tisíce',
        many: 'tisícov',
        other: 'tisíce',
      },
      abbr: {
        other: 'tis.',
      },
    },
    million: {
      words: {
        one: 'milión',
        few: 'milióny',
        many: 'miliónov',
        other: 'milióny',
      },
      abbr: {
        other: 'mil.',
      },
    },
    billion: {
      words: {
        one: 'miliarda',
        few: 'miliardy',
        many: 'miliárd',
        other: 'miliardy',
      },
      abbr: {
        other: 'mld.',
      },
    },
    trillion: {
      words: {
        one: 'bilión',
        few: 'bilióny',
        many: 'biliónov',
        other: 'bilióny',
      },
      abbr: {
        other: 'bln.',
      },
    },
  },
} as any as LocalePack;

export default pack;
