
// Auto-generated by scripts/generate-locales.ts
import type { LocalePack } from '../src/precise-compact';

const pack = {
  "locale": "sl",
  "labels": {
    "thousand": {
      "words": {
        "one": "tisoč",
        "other": "tisoči"
      },
      "abbr": {
        "other": "tis."
      }
    },
    "million": {
      "words": {
        "one": "milijon",
        "other": "milijoni"
      },
      "abbr": {
        "other": "mio."
      }
    },
    "billion": {
      "words": {
        "one": "milijarda",
        "other": "milijarde"
      },
      "abbr": {
        "other": "mrd."
      }
    },
    "trillion": {
      "words": {
        "one": "bilijon",
        "other": "bilijoni"
      },
      "abbr": {
        "other": "bln."
      }
    }
  }
} as any as LocalePack;

export default pack;
