// comments in English only
// Auto-generated by scripts/generate-locales.ts
import type { LocalePack } from '../src/precise-compact';

const pack = {
  "locale": "sr",
  "labels": {
    "thousand": {
      "words": {
        "one": "хиљада",
        "few": "хиљаде",
        "many": "хиљада",
        "other": "хиљаде"
      },
      "abbr": {
        "other": "хиљ."
      }
    },
    "million": {
      "words": {
        "one": "милион",
        "few": "милиона",
        "many": "милиона",
        "other": "милиона"
      },
      "abbr": {
        "other": "млн."
      }
    },
    "billion": {
      "words": {
        "one": "милијарда",
        "few": "милијарде",
        "many": "милијарди",
        "other": "милијарде"
      },
      "abbr": {
        "other": "млрд."
      }
    },
    "trillion": {
      "words": {
        "one": "трилион",
        "few": "трилиона",
        "many": "трилиона",
        "other": "трилиона"
      },
      "abbr": {
        "other": "трлн."
      }
    }
  }
} as any as LocalePack;

export default pack;
