
// Auto-generated by scripts/generate-locales.ts
import type { LocalePack } from '../src/precise-compact';

const pack = {
  "locale": "sv",
  "labels": {
    "thousand": {
      "words": "tusen",
      "abbr": "tus"
    },
    "million": {
      "words": {
        "one": "miljon",
        "other": "miljoner"
      },
      "abbr": {
        "other": "mn"
      }
    },
    "billion": {
      "words": {
        "one": "miljard",
        "other": "miljarder"
      },
      "abbr": {
        "other": "md"
      }
    },
    "trillion": {
      "words": {
        "one": "biljon",
        "other": "biljoner"
      },
      "abbr": {
        "other": "bln"
      }
    }
  }
} as any as LocalePack;

export default pack;
