// comments in English only
// Auto-generated by scripts/generate-locales.ts
import type { LocalePack } from '../src/precise-compact';

const pack = {
  locale: 'sw',
  labels: {
    thousand: {
      words: 'elfu',
      abbr: 'elf',
    },
    million: {
      words: 'milioni',
      abbr: 'M',
    },
    billion: {
      words: 'bilioni',
      abbr: 'Bn',
    },
    trillion: {
      words: 'trilioni',
      abbr: 'Tn',
    },
  },
} as any as LocalePack;

export default pack;
