// comments in English only
// Auto-generated by scripts/generate-locales.ts
import type { LocalePack } from '../src/precise-compact';

const pack = {
  locale: 'te',
  labels: {
    thousand: {
      words: 'వేలు',
      abbr: 'వే',
    },
    million: {
      words: 'మిలియన్',
      abbr: 'మి',
    },
    billion: {
      words: 'బిలియన్',
      abbr: 'బి',
    },
    trillion: {
      words: 'ట్రిలియన్',
      abbr: 'ట్రి',
    },
  },
} as any as LocalePack;

export default pack;
