
// Auto-generated by scripts/generate-locales.ts
import type { LocalePack } from '../src/precise-compact';

const pack = {
  "locale": "th",
  "labels": {
    "thousand": {
      "words": "พัน",
      "abbr": "พัน"
    },
    "million": {
      "words": "ล้าน",
      "abbr": "ล"
    },
    "billion": {
      "words": "พันล้าน",
      "abbr": "พ.ล"
    },
    "trillion": {
      "words": "ล้านล้าน",
      "abbr": "ล.ล"
    }
  }
} as any as LocalePack;

export default pack;
