
// Auto-generated by scripts/generate-locales.ts
import type { LocalePack } from '../src/precise-compact';

const pack = {
  "locale": "tr",
  "labels": {
    "thousand": {
      "words": "bin",
      "abbr": "B"
    },
    "million": {
      "words": "milyon",
      "abbr": "Mn"
    },
    "billion": {
      "words": "milyar",
      "abbr": "Mr"
    },
    "trillion": {
      "words": "trilyon",
      "abbr": "Tr"
    }
  }
} as any as LocalePack;

export default pack;
