// comments in English only
// Auto-generated by scripts/generate-locales.ts
import type { LocalePack } from '../src/precise-compact';

const pack = {
  "locale": "uk",
  "labels": {
    "thousand": {
      "words": {
        "one": "тисяча",
        "few": "тисячі",
        "many": "тисяч",
        "other": "тисячі"
      },
      "abbr": {
        "other": "тис."
      }
    },
    "million": {
      "words": {
        "one": "мільйон",
        "few": "мільйона",
        "many": "мільйонів",
        "other": "мільйона"
      },
      "abbr": {
        "other": "млн"
      }
    },
    "billion": {
      "words": {
        "one": "мільярд",
        "few": "мільярда",
        "many": "мільярдів",
        "other": "мільярда"
      },
      "abbr": {
        "other": "млрд"
      }
    },
    "trillion": {
      "words": {
        "one": "трильйон",
        "few": "трильйона",
        "many": "трильйонів",
        "other": "трильйона"
      },
      "abbr": {
        "other": "трлн"
      }
    }
  }
} as any as LocalePack;

export default pack;
