
// Auto-generated by scripts/generate-locales.ts
import type { LocalePack } from '../src/precise-compact';

const pack = {
  "locale": "ur",
  "labels": {
    "thousand": {
      "words": "ہزار",
      "abbr": "ہ"
    },
    "million": {
      "words": "ملین",
      "abbr": "مل"
    },
    "billion": {
      "words": "بلین",
      "abbr": "بل"
    },
    "trillion": {
      "words": "ٹریلین",
      "abbr": "ٹر"
    }
  },
  "rules": {
    "rtl": true
  }
} as any as LocalePack;

export default pack;
