// comments in English only
// Auto-generated by scripts/generate-locales.ts
import type { LocalePack } from '../src/precise-compact';

const pack = {
  locale: 'zh-TW',
  labels: {
    thousand: {
      words: '千',
      abbr: '千',
    },
    million: {
      words: '百萬',
      abbr: '百萬',
    },
    billion: {
      words: '十億',
      abbr: '十億',
    },
    trillion: {
      words: '兆',
      abbr: '兆',
    },
  },
  rules: {
    joiner: '',
    numberLocale: 'zh-TW',
  },
} as any as LocalePack;

export default pack;
