name: Cleanup old workflow runs

on:
  schedule:
    # Запускать каждый понедельник в 00:00 UTC
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  cleanup:
    name: Delete old workflow runs
    runs-on: ubuntu-latest
    permissions:
      actions: write

    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 30
          keep_minimum_runs: 6
